
backend:
  name: github
  repo: mexac/e-commerce-shopeasetz   # Hakikisha hili jina la mradi liko sahihi kabisa
  branch: main
  base_url: https://shopease.co.tz
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "Bidhaa (Products)"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Jina la Nguo", name: "title", widget: "string" }
      - { label: "Bei (Tsh)", name: "price", widget: "number", value_type: "int" }
      - { label: "Kundi (Category)", name: "category", widget: "select", options: ["Jeans", "Dress", "Shirts", "T-Shirts"] }
      - { label: "Picha ya Nguo", name: "image", widget: "image" }
      - { label: "Maelezo ya Ziada", name: "body", widget: "markdown", required: false }
